# Generated by Django 5.0.6 on 2024-05-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('cant_entradas', models.IntegerField()),
                ('autos', models.ManyToManyField(to='vehiculos.vehiculos_list')),
            ],
        ),
    ]
