# Generated by Django 5.0.6 on 2024-05-13 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_personas_list_vehiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculos_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas_list')),
            ],
        ),
    ]
