# Generated by Django 5.0.6 on 2024-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos_list',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
