# Generated by Django 5.0.6 on 2024-05-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas_list',
            name='vehiculo',
            field=models.BooleanField(default=False),
        ),
    ]
